application: tropy-page
version: 2
runtime: python
api_version: 1

handlers:
- url: /(.*\.ico)
  static_files: ico/\1
  upload: ico/(.*\.ico)

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: tropy.py
